# Generated by Django 3.2 on 2023-04-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('createsignal', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createsignal.cryptosignal')),
                ('forex_signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createsignal.forexsignal')),
            ],
        ),
    ]
