# Generated by Django 3.2 on 2023-04-18 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createsignal', '0003_cryptosignal2_forexsignal2'),
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createsignal.cryptosignal2')),
                ('forex_signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createsignal.forexsignal2')),
            ],
        ),
    ]
