# Generated by Django 3.2 on 2023-04-18 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyAccount2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=256)),
                ('referral_code', models.CharField(max_length=50)),
                ('referral_link', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('account_balance', models.IntegerField(default=0)),
                ('account_number', models.CharField(max_length=20)),
                ('gmail', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasport_image_front', models.ImageField(upload_to='image/')),
                ('pasport_image_back', models.ImageField(upload_to='image/')),
                ('verify_link', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
