# Generated by Django 3.2 on 2023-04-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_watch', models.CharField(choices=[('EURUSD', 'EURUSD'), ('EURCHF', 'EURCHF'), ('EURGBP', 'EURGBP'), ('EURJPY', 'EURJPY'), ('EURAUD', 'EURAUD'), ('EURNZD', 'EURNZD'), ('EURCAD', 'EURCAD'), ('USDJPY', 'USDJPY'), ('USDCAD', 'USDCAD'), ('USDCHF', 'USDCHF'), ('CADCHF', 'CADCHF'), ('CADJPY', 'CADJPY'), ('CHFJPY', 'CHFJPY'), ('GBPJPY', 'GBPJPY'), ('GBPCHF', 'GBPCHF'), ('GBPUSD', 'GBPUSD'), ('GBPNZD', 'GBPNZD'), ('GBPAUD', 'GBPAUD'), ('GBPCAD', 'GBPCAD'), ('AUDUSD', 'AUDUSD'), ('AUDCAD', 'AUDCAD'), ('AUDCHF', 'AUDCHF'), ('AUDJPY', 'AUDJPY'), ('AUDNZD', 'AUDNZD'), ('NZDUSD', 'NZDUSD'), ('NZDCAD', 'NZDCAD'), ('NZDCHF', 'NZDCHF'), ('NZDJPY', 'NZDJPY'), ('XAUUSD', 'XAUUSD')], max_length=20)),
                ('live_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('signal_type', models.CharField(choices=[('sell', 'sell'), ('buy', 'buy'), ('sell limit', 'sell limit'), ('sell stop', 'sell stop'), ('buy limit', 'buy limit'), ('buy stop', 'buy stop')], max_length=25)),
                ('entry_price', models.IntegerField(blank=True, default=0, null=True)),
                ('take_profit', models.IntegerField(blank=True, default=0, null=True)),
                ('stop_loss', models.IntegerField(blank=True, default=0, null=True)),
                ('crypto_winrate', models.IntegerField(blank=True, default=0, null=True)),
                ('total_stop_loss', models.IntegerField(blank=True, default=0, null=True)),
                ('total_take_profit', models.IntegerField(blank=True, default=0, null=True)),
                ('total_stop_loss_pips', models.IntegerField(blank=True, default=0, null=True)),
                ('total_take_profit_pips', models.IntegerField(blank=True, default=0, null=True)),
                ('total_signal', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForexSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_watch', models.CharField(choices=[('EURUSD', 'EURUSD'), ('EURCHF', 'EURCHF'), ('EURGBP', 'EURGBP'), ('EURJPY', 'EURJPY'), ('EURAUD', 'EURAUD'), ('EURNZD', 'EURNZD'), ('EURCAD', 'EURCAD'), ('USDJPY', 'USDJPY'), ('USDCAD', 'USDCAD'), ('USDCHF', 'USDCHF'), ('CADCHF', 'CADCHF'), ('CADJPY', 'CADJPY'), ('CHFJPY', 'CHFJPY'), ('GBPJPY', 'GBPJPY'), ('GBPCHF', 'GBPCHF'), ('GBPUSD', 'GBPUSD'), ('GBPNZD', 'GBPNZD'), ('GBPAUD', 'GBPAUD'), ('GBPCAD', 'GBPCAD'), ('AUDUSD', 'AUDUSD'), ('AUDCAD', 'AUDCAD'), ('AUDCHF', 'AUDCHF'), ('AUDJPY', 'AUDJPY'), ('AUDNZD', 'AUDNZD'), ('NZDUSD', 'NZDUSD'), ('NZDCAD', 'NZDCAD'), ('NZDCHF', 'NZDCHF'), ('NZDJPY', 'NZDJPY'), ('XAUUSD', 'XAUUSD')], max_length=20)),
                ('live_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('signal_type', models.CharField(choices=[('sell', 'sell'), ('buy', 'buy'), ('sell limit', 'sell limit'), ('sell stop', 'sell stop'), ('buy limit', 'buy limit'), ('buy stop', 'buy stop')], max_length=25)),
                ('entry_price', models.IntegerField(blank=True, default=0, null=True)),
                ('take_profit', models.IntegerField(blank=True, default=0, null=True)),
                ('stop_loss', models.IntegerField(blank=True, default=0, null=True)),
                ('forex_winrate', models.IntegerField(blank=True, default=0, null=True)),
                ('total_stop_loss', models.IntegerField(blank=True, default=0, null=True)),
                ('total_take_profit', models.IntegerField(blank=True, default=0, null=True)),
                ('total_stop_loss_pips', models.IntegerField(blank=True, default=0, null=True)),
                ('total_take_profit_pips', models.IntegerField(blank=True, default=0, null=True)),
                ('total_signal', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
